### ISSUE TITLE
Startying Cyphondock_nginx_1 .... error

### ISSUE THREAD

**Issue by tee2015** [dunbarcyber/cyphondock#16]
I was following the document installing Cyphon all went well untill i use this command: sudo docker-compose up -d
 and i gave me back: Startying Cyphondock_nginx_1 .... error 
Error: Cyphondock_nginx_1 cannot start service nginx ....................................
proxy: listen tcp 0.0.0.0:80 bind : address already in use 

Ok i think i know my mistake i have already nginx installed on my server i think this will be the problem what  do you think guys ?
I am very exited to this project because it is the first time i install docker but i miss the whole idea of docking  once i start install the web server and the postgress in the traditional way !!! 
Cheers.

**Comment by lhadjchikh** [comment]
You can change it to a different port in [line 32 of docker-compose.override.yml](https://github.com/dunbarcyber/cyphondock/blob/master/docker-compose.override.yml#L32) and 
[line 12 of config/nginx/nginx.conf](https://github.com/dunbarcyber/cyphondock/blob/master/config-COPYME/nginx/nginx.conf#L12). 

You could also bind the ports from the containers directly to your host machine, instead of proxying them through Nginx. For example, in `docker-compose.override.yml`, you'd get rid of the `nginx` service and instead configure the ports for the containers it was proxying, e.g.:
```
version: '2'

services:

  cyclops:
    env_file:
      - ./config/env/cyclops.env
    volumes:
      - ./config/env/cyclops.env:/usr/src/app/cyclops/cyclops.env
    ports:
      - "81:81"

 cyphon:
    ports: 
      - "8000:8000"

  kibana:
    ports: 
      - "5601:5601"

  rabbit:
    ports: 
      - "15672:15672"

  elasticsearch:
    volumes:
      - /opt/cyphon/data/elasticsearch:/usr/share/elasticsearch/data

  logstash:
    ports:
      - "5044:5044"
      - "5045:5045"  # you can configure Filebeat to send Nessus files here

  postgres:
    volumes:
      - /opt/cyphon/data/postgresql:/var/lib/postgresql/data 
```
Then you'd be able to access Cyclops at localhost:81 and Cyphon at localhost:8000, without going through Nginx.
