### ISSUE TITLE
Dedicated logstash to Cyphondcok-Elasticsearch

### ISSUE THREAD

**Issue by suchandbabu** [dunbarcyber/cyphondock#52]
Please share the configuration to forward logs from a dedicated logstash instance to Cyphondock elasticsearch.

**Comment by lhadjchikh** [comment]
Modify the `docker-compose-override.yml` file to bind port 9200 of the container to the same port on the host:
```
  elasticsearch:
    volumes:
      - ../data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
```
Then configure your Logstash output to point to the host where your Elasticsearch container is running.
